[DPE-3726] Release 3.8.4-ubuntu0
canonical/zookeeper-rock pull request #4
Opened 2024-03-08 14:44 UTC by deusebio

2024-03-08 14:46 UTC, zmraul approved these changes

2024-03-08 17:17 UTC, grobbie requested changes
JDK 8? Needs to be 19 I believe.

2024-03-09 15:50 UTC, deusebio commented
> JDK 8? Needs to be 19 I believe.

This is quite interesting. I had been digging this a bit more. Interestingly: 

1. In the zookeeper main repo the JDK that is generally used is 8 (e.g. [here](https://github.com/search?q=repo%3Aapache%2Fzookeeper%20jdk&type=code)). 

2. The [doc](https://zookeeper.apache.org/doc/r3.8.4/zookeeperAdmin.html) says that 

> ZooKeeper runs in Java, release 1.8 or greater (JDK 8 LTS, JDK 11 LTS, JDK 12 - Java 9 and 10 are not supported)

3. The tests in the CI/CD are against 8 and 11, see [here](https://github.com/apache/zookeeper/blob/master/.github/workflows/ci.yaml#L34).  

4. [someone in the mailing list](https://lists.apache.org/list?user@zookeeper.apache.org:2023-4:jdk) says that they are running in production on JDK 19 with no issues.

5. ZooKeeper successfully builds on JDK 21 LTS as well, see logs [here](https://ci-hadoop.apache.org/view/ZooKeeper/job/ZooKeeper-Java-EA/lastBuild/consoleFull) 

Although it is *probably* all right to even jump to JDK 21, maybe it is just safer here to start bumping to JDK 11 (and we would already be better off than the upstream image that uses 8). We could probably have (but outside of this PR) also another branch for JDK 21, which we tag as edge. 

But I need to first start the integration on the OCI factory with a version we are solid with (say 11) and then open another track (but I need to discuss with Cris on the naming of the tag probably).

2024-03-11 14:55 UTC, grobbie approved these changes
LGTM

2024-03-11 15:25 UTC, merged